"""Increase password hash field size

Revision ID: c311b91558d5
Revises: 26f0170045af
Create Date: 2025-03-05 16:21:50.626318

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c311b91558d5'
down_revision = '26f0170045af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('gender',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=256),
               existing_nullable=True)
        batch_op.alter_column('locale',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=256),
               existing_nullable=True)
        batch_op.alter_column('location',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=256),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('location',
               existing_type=sa.String(length=256),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
        batch_op.alter_column('locale',
               existing_type=sa.String(length=256),
               type_=sa.VARCHAR(length=10),
               existing_nullable=True)
        batch_op.alter_column('gender',
               existing_type=sa.String(length=256),
               type_=sa.VARCHAR(length=10),
               existing_nullable=True)

    # ### end Alembic commands ###
