"""Add recommendation enhancements

Revision ID: c40d5b873ab3
Revises: c311b91558d5
Create Date: 2025-03-08 22:47:15.157954

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c40d5b873ab3'
down_revision = 'c311b91558d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_event_interactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('interaction_type', sa.String(length=50), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('interaction_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('end_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('category', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('subcategory', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('max_attendees', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('is_featured', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('latitude', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('longitude', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('event_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True))

    with op.batch_alter_table('event_attendees', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('synced_to_calendar', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('calendar_event_id', sa.String(length=256), nullable=True))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('google_calendar_token', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('google_calendar_refresh_token', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('google_calendar_token_expiry', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('calendar_sync_enabled', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('precise_location_enabled', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('latitude', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('longitude', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('preferences', postgresql.JSONB(astext_type=sa.Text()), nullable=True))

    with op.batch_alter_table('user_interests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('strength', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_interests', schema=None) as batch_op:
        batch_op.drop_column('created_at')
        batch_op.drop_column('strength')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('preferences')
        batch_op.drop_column('longitude')
        batch_op.drop_column('latitude')
        batch_op.drop_column('precise_location_enabled')
        batch_op.drop_column('calendar_sync_enabled')
        batch_op.drop_column('google_calendar_token_expiry')
        batch_op.drop_column('google_calendar_refresh_token')
        batch_op.drop_column('google_calendar_token')

    with op.batch_alter_table('event_attendees', schema=None) as batch_op:
        batch_op.drop_column('calendar_event_id')
        batch_op.drop_column('synced_to_calendar')
        batch_op.drop_column('status')

    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.drop_column('event_metadata')
        batch_op.drop_column('longitude')
        batch_op.drop_column('latitude')
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')
        batch_op.drop_column('is_featured')
        batch_op.drop_column('max_attendees')
        batch_op.drop_column('subcategory')
        batch_op.drop_column('category')
        batch_op.drop_column('end_date')

    op.drop_table('user_event_interactions')
    # ### end Alembic commands ###
